// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     TSTypesJenny
//     LatestMajorsOrXJenny
//
// Run 'make gen-cue' from repository root to regenerate.

export interface Folder {
  /**
   * Folder title (must be unique within the parent folder)
   */
  title: string;
  /**
   * Folder UID
   */
  uid: string;
}
