// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     TSTypesJenny
//     LatestMajorsOrXJenny
//
// Run 'make gen-cue' from repository root to regenerate.

export interface Folder {
  /**
   * Folder description
   */
  description?: string;
  /**
   * Parend folder UID
   * TODO: ideally this should be identified the same way as dashboards+library panels
   * NOTE: only used when the nestedFolder feature flag is enabled
   */
  parentUid?: string;
  /**
   * Folder title (must be unique within the parent folder)
   */
  title: string;
  /**
   * Folder UID
   */
  uid: string;
}
