// Code generated - EDITING IS FUTILE. DO NOT EDIT.
//
// Generated by:
//     kinds/gen.go
// Using jennies:
//     CRDTypesJenny
//
// Run 'make gen-cue' from repository root to regenerate.

package crd

import (
	_ "embed"

	"github.com/grafana/grafana/pkg/kinds/folder"
	"github.com/grafana/grafana/pkg/kindsys/k8ssys"
)

// The CRD YAML representation of the Folder kind.
//
//go:embed folder.crd.yml
var CRDYaml []byte

// Folder is the Go CRD representation of a single Folder object.
// It implements [runtime.Object], and is used in k8s scheme construction.
type Folder struct {
	k8ssys.Base[folder.Folder]
}

// FolderList is the Go CRD representation of a list Folder objects.
// It implements [runtime.Object], and is used in k8s scheme construction.
type FolderList struct {
	k8ssys.ListBase[folder.Folder]
}
